devices:
# change this to a keyboard device
- "/dev/input/by-path/platform-i8042-serio-0-event-kbd"
# this is executed when mouseless starts
# startCommand: ""
# the default speed for mouse movement
baseMouseSpeed: 750.0
# the default speed for scrolling
baseScrollSpeed: 20.0
layers:
# the first layer is active at start
- name: initial
  bindings:
    # when rightalt is held and another key pressed, activate mouse layer
    rightalt: tap-hold-next tab ; layer mouse ; 500
    # when a is held for 300ms, activate mouse layer
    # right alt key toggles arrows layer
# a layer for mouse movement
- name: mouse
  # when true, keys that are not mapped keep their original meaning
  passThrough: true
  bindings:
    # quit mouse layer
    q: layer initial
    # keep the mouse layer active
    space: speed 0.2
    r: reload-config
    l: move  1  0
    j: move -1  0
    k: move  0  1
    i: move  0 -1
    p: scroll up
    n: scroll down
    a: button left
    u: button left
    s: button middle
    d: button right
    o: button right
    k9: scroll up
    k8: scroll down
    # move to the top left corner
    k0: move 5 10
# another layer for arrows and some other keys
- name: arrows
  passThrough: true
  bindings:
